# Generated by Django 3.0.8 on 2020-07-26 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AL', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('AK', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('AZ', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('AR', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('CA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('CO', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('CT', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('DC2', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('DE', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('FL', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('GA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('HI', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('IDA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('IL', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('IN', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('IA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('KS', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('KY', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('LA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('ME', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('MD', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('MA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('MI', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('MN', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('MS', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('MO', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('MT', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('NE', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('NV', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('NH', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('NJ', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('NM', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('NY', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('NC', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('ND', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('OH', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('OK', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('OR', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('PA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('RI', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('SC', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('SD', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('TN', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('TX', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('UT', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('VT', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('VA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('WA', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('WV', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('WI', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('WY', models.CharField(choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
