# Generated by Django 3.0.8 on 2020-07-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictit2020_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='electoral_votes_dem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='electoral_votes_rep',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
