# Generated by Django 3.0.8 on 2020-08-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictit2020_backend', '0004_auto_20200728_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='AK',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='AL',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='AR',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='AZ',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='CA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='CO',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='CT',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='DC2',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='DE',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='FL',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='GA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='HI',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='IA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='IDA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='IL',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='IN',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='KS',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='KY',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='LA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='MA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='MD',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='ME',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='MI',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='MN',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='MO',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='MS',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='MT',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='NC',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='ND',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='NE',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='NH',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='NJ',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='NM',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='NV',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='NY',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='OH',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='OK',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='OR',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='PA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='RI',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='SC',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='SD',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='TN',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='TX',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='UT',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='VA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='VT',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='WA',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='WI',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='WV',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='WY',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='electoral_votes_dem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='electoral_votes_rep',
            field=models.IntegerField(default=0),
        ),
    ]
