# Generated by Django 3.0.8 on 2020-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictit2020_backend', '0005_auto_20200819_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='ME',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican'), ('d2r2', 'd2r2'), ('d3r1', 'd3r1'), ('d1r3', 'd1r3')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='NE',
            field=models.CharField(blank=True, choices=[('d', 'Democrat'), ('r', 'Republican'), ('d1r4', 'd1r4'), ('d2r3', 'd2r3'), ('d3r2', 'd3r2'), ('d4r1', 'd4r1')], max_length=4, null=True),
        ),
    ]
